// <auto-generated />
using System;
using IU2_Test.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IU2_Test.Migrations
{
    [DbContext(typeof(MyDatabase))]
    [Migration("20210104110138_Added Relation table.")]
    partial class AddedRelationtable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("IU2_Test.Models.DoorType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("DoorTypes");
                });

            modelBuilder.Entity("IU2_Test.Models.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("IU2_Test.Models.Relation", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("doorTypeIDID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("eventIDID")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("tenantIDID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("doorTypeIDID");

                    b.HasIndex("eventIDID");

                    b.HasIndex("tenantIDID");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("IU2_Test.Models.Tenant", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApartmentNum")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("IU2_Test.Models.Relation", b =>
                {
                    b.HasOne("IU2_Test.Models.DoorType", "doorTypeID")
                        .WithMany()
                        .HasForeignKey("doorTypeIDID");

                    b.HasOne("IU2_Test.Models.Event", "eventID")
                        .WithMany()
                        .HasForeignKey("eventIDID");

                    b.HasOne("IU2_Test.Models.Tenant", "tenantID")
                        .WithMany()
                        .HasForeignKey("tenantIDID");

                    b.Navigation("doorTypeID");

                    b.Navigation("eventID");

                    b.Navigation("tenantID");
                });
#pragma warning restore 612, 618
        }
    }
}
