// <auto-generated />
using EFDemo.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFDemo.Migrations
{
    [DbContext(typeof(FilmLista))]
    partial class FilmListaModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EFDemo.Controllers.Film", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Betyg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EngTitel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .HasColumnType("TEXT");

                    b.Property<int>("Url")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Filmer");
                });
#pragma warning restore 612, 618
        }
    }
}
