// <auto-generated />
using System;
using HusrumProject.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HusrumProject.Migrations
{
    [DbContext(typeof(DatabaseFilePath))]
    [Migration("20210117185419_Husrum")]
    partial class Husrum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("HusrumProject.Models.DoorEvent", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("DoorEvents");
                });

            modelBuilder.Entity("HusrumProject.Models.DoorLocation", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("DoorLocations");
                });

            modelBuilder.Entity("HusrumProject.Models.DoorName", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("DoorNames");
                });

            modelBuilder.Entity("HusrumProject.Models.EventLog", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DoorEventID")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DoorNameID")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("TenantID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("DoorEventID");

                    b.HasIndex("DoorNameID");

                    b.HasIndex("TenantID");

                    b.ToTable("EventLogs");
                });

            modelBuilder.Entity("HusrumProject.Models.Tenant", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LocationID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenantTag")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("LocationID");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("HusrumProject.Models.EventLog", b =>
                {
                    b.HasOne("HusrumProject.Models.DoorEvent", "DoorEvent")
                        .WithMany()
                        .HasForeignKey("DoorEventID");

                    b.HasOne("HusrumProject.Models.DoorName", "DoorName")
                        .WithMany()
                        .HasForeignKey("DoorNameID");

                    b.HasOne("HusrumProject.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantID");

                    b.Navigation("DoorEvent");

                    b.Navigation("DoorName");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("HusrumProject.Models.Tenant", b =>
                {
                    b.HasOne("HusrumProject.Models.DoorLocation", "Location")
                        .WithMany()
                        .HasForeignKey("LocationID");

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
