// <auto-generated />
using System;
using ApartmentDBEF.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApartmentDBEF.Migrations
{
    [DbContext(typeof(ApartmentDB))]
    partial class ApartmentDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("ApartmentDBEF.Models.Action", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actions")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("ApartmentDBEF.Models.Apartment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apartmentnumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDDoor")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("ApartmentDBEF.Models.Code", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Codes");
                });

            modelBuilder.Entity("ApartmentDBEF.Models.Door", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApartmentID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Doorname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Doors");
                });

            modelBuilder.Entity("ApartmentDBEF.Models.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IDAction")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDDoor")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDTag")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("ApartmentDBEF.Models.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDApartment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDTenant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tagnumber")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ApartmentDBEF.Models.Tenant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDApartment")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IDTag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Tenants");
                });
#pragma warning restore 612, 618
        }
    }
}
